CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ecdsa_public_key TEXT NOT NULL UNIQUE,
    is_samaritan BOOLEAN NOT NULL DEFAULT FALSE,
    push_token TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS emergencies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_user_id BIGINT NOT NULL REFERENCES users(id),
    requested_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    latitude DOUBLE PRECISION NOT NULL CHECK (latitude BETWEEN -90 AND 90),
    longitude DOUBLE PRECISION NOT NULL CHECK (longitude BETWEEN -180 AND 180),
    requires_911 BOOLEAN NOT NULL DEFAULT FALSE,
    emergency_type TEXT,
    self_emergency TEXT,
    description TEXT
);

CREATE INDEX IF NOT EXISTS emergencies_requested_at_idx ON emergencies (requested_at DESC);
CREATE INDEX IF NOT EXISTS emergencies_coordinates_idx ON emergencies (latitude, longitude);

CREATE TABLE IF NOT EXISTS emergency_acceptances (
    emergency_id BIGINT NOT NULL REFERENCES emergencies(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES users(id),
    accepted_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (emergency_id, user_id)
);

CREATE TABLE IF NOT EXISTS emergency_locations (
    emergency_id BIGINT NOT NULL REFERENCES emergencies(id) ON DELETE CASCADE,
    label TEXT NOT NULL CHECK (label IN ('requester', 'responder')),
    latitude DOUBLE PRECISION NOT NULL CHECK (latitude BETWEEN -90 AND 90),
    longitude DOUBLE PRECISION NOT NULL CHECK (longitude BETWEEN -180 AND 180),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (emergency_id, label)
);