spring.application.name=websocket
samaritan.ws.allowed-origins=*
spring.datasource.url=${SAMARITAN_DB_URL:jdbc:postgresql://uwb0xcqrge.wydp0t3kyk.tsdb.cloud.timescale.com:31357/tsdb?sslmode=require}
spring.datasource.username=${SAMARITAN_DB_USERNAME:tsdbadmin}
spring.datasource.password=${SAMARITAN_DB_PASSWORD:}
spring.data.
